services:
  # Go
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - REFRESH_TOKEN=${REFRESH_TOKEN}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - USERNAME_ADMIN=${USERNAME_ADMIN}
      - PASSWORD_ADMIN=${PASSWORD_ADMIN}
      - EMAIL_ADMIN=${EMAIL_ADMIN}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_ADDR=${REDIS_ADDR}

  # PostgresSQL
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

    # Redis
  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data: